name: github-ci

on:
  push:
    tags: 
      - '*'

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:      
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '19.4.0'
          cache: 'pnpm'
      - name: Run test
        run: pnpm install && pnpm run test

  build-and-push-to-gcr:
    name: Build and push image to gcr
    needs: unit-test
    runs-on: ubuntu-latest
    env:
      REGISTRY: gcr.io/${{ secrets.GCP_PROJECT_ID }}
      IMAGE: ${REGISTRY}/gf-server:${GITHUB_REF_NAME}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@v0
      # Build docker image
      - name: Build image
        run: |-
          docker build -t ${{ env.IMAGE }} .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push image
        run: |-
          docker push ${{ env.IMAGE }}